# Generated by Django 5.2.5 on 2025-08-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
