# Generated by Django 5.2.5 on 2025-08-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_emoji_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='product',
            name='emoji',
        ),
    ]
