# Generated by Django 5.2.5 on 2025-08-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productcolor_productsize_delete_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolor',
            old_name='color',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='stock',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='hex_code',
            field=models.CharField(blank=True, help_text='مثلا #FF5733', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
